/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tech.calaverita.views;

import java.awt.BorderLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import tech.calaverita.bd.Conexion;

/**
 *
 * @author memoc
 */
public class Biblioteca extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Biblioteca() {
        initComponents();

        Principal p0 = new Principal();
        p0.setSize(600, 400);
        p0.setLocation(0, 0);

        this.Contenido.removeAll();
        this.Contenido.add(p0, BorderLayout.CENTER);
        this.Contenido.revalidate();
        this.Contenido.repaint();
        
        try {
            Conexion.getConnection();
        } catch (SQLException ex) {
            Logger.getLogger(Biblioteca.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void setContenido(JPanel p1) {

        p1.setSize(600, 400);
        p1.setLocation(0, 0);

        this.Contenido.removeAll();
        this.Contenido.add(p1, BorderLayout.CENTER);
        this.Contenido.revalidate();
        this.Contenido.repaint();
    }
    
    public void setCabecera(String cabecera){
        this.Cabecera.setText(cabecera);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        Cabecera = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Libros = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Usuarios = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Prestamos = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Autores = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Principal = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Contenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(0, 153, 255));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cabecera.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        Cabecera.setForeground(new java.awt.Color(255, 255, 255));
        Cabecera.setText("Principal");
        Header.add(Cabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        Background.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 600, 100));

        Menu.setBackground(new java.awt.Color(51, 102, 255));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Escolar");
        Menu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 190, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Biblioteca");
        Menu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 200, 40));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        Menu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 150, 10));

        Libros.setBackground(new java.awt.Color(51, 102, 255));
        Libros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LibrosMousePressed(evt);
            }
        });
        Libros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/book-open-page-variant.png"))); // NOI18N
        jLabel6.setText(" Libros");
        Libros.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 0, 90, 40));

        Menu.add(Libros, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 190, 40));

        Usuarios.setBackground(new java.awt.Color(51, 102, 255));
        Usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UsuariosMousePressed(evt);
            }
        });
        Usuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/account-multiple.png"))); // NOI18N
        jLabel3.setText(" Usuarios");
        Usuarios.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 40));

        Menu.add(Usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 190, 40));

        Prestamos.setBackground(new java.awt.Color(51, 102, 255));
        Prestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PrestamosMousePressed(evt);
            }
        });
        Prestamos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calendar-plus.png"))); // NOI18N
        jLabel4.setText(" Prestamos");
        Prestamos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 40));

        Menu.add(Prestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 190, 40));

        Autores.setBackground(new java.awt.Color(51, 102, 255));
        Autores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AutoresMousePressed(evt);
            }
        });
        Autores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file-chart.png"))); // NOI18N
        jLabel5.setText(" Autores");
        Autores.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 40));

        Menu.add(Autores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 190, 40));

        Principal.setBackground(new java.awt.Color(51, 102, 255));
        Principal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PrincipalMousePressed(evt);
            }
        });
        Principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home-outline.png"))); // NOI18N
        jLabel7.setText(" Principal");
        Principal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 40));

        Menu.add(Principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 190, 40));

        Background.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 500));

        Contenido.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ContenidoLayout = new javax.swing.GroupLayout(Contenido);
        Contenido.setLayout(ContenidoLayout);
        ContenidoLayout.setHorizontalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        ContenidoLayout.setVerticalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        Background.add(Contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 600, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrincipalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrincipalMousePressed
        // TODO add your handling code here:
        Principal p1 = new Principal();
        this.setContenido(p1);
        this.setCabecera("Principal");
    }//GEN-LAST:event_PrincipalMousePressed

    private void UsuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsuariosMousePressed
        // TODO add your handling code here:
        Usuarios p1 = new Usuarios(this);
        this.setContenido(p1);
        this.setCabecera("Usuarios");
    }//GEN-LAST:event_UsuariosMousePressed

    private void LibrosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LibrosMousePressed
        // TODO add your handling code here:
        Libros p1 = new Libros(this);
        this.setContenido(p1);
        this.setCabecera("Libros");
    }//GEN-LAST:event_LibrosMousePressed

    private void AutoresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AutoresMousePressed
        // TODO add your handling code here:
        Autores p1 = new Autores(this);
        this.setContenido(p1);
        this.setCabecera("Autores");
    }//GEN-LAST:event_AutoresMousePressed

    private void PrestamosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrestamosMousePressed
        // TODO add your handling code here:
        Prestamos p1 = new Prestamos(this);
        this.setContenido(p1);
        this.setCabecera("Prestamos");
    }//GEN-LAST:event_PrestamosMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Biblioteca().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Autores;
    private javax.swing.JPanel Background;
    private javax.swing.JLabel Cabecera;
    private javax.swing.JPanel Contenido;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Libros;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel Prestamos;
    private javax.swing.JPanel Principal;
    private javax.swing.JPanel Usuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
