/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tech.calaverita.views;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import tech.calaverita.idao.PrestamoDaoJdbc;
import tech.calaverita.models.Prestamo;

/**
 *
 * @author memoc
 */
public class Devolucion extends javax.swing.JPanel {

    /**
     * Creates new form Devolucion
     */
    PrestamoDaoJdbc prestamoDaoJdbc;
    Prestamo prestamo;

    public Devolucion() {
        initComponents();
        prestamoDaoJdbc = new PrestamoDaoJdbc();
        this.Devuelto.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jLabel5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        libroId = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Devolver = new javax.swing.JButton();
        usuarioId = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Devuelto = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iStock.jpg"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 40, 340, 390));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 10, 270));

        libroId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        libroId.setForeground(new java.awt.Color(204, 204, 204));
        libroId.setText("Ingrese el id del libro");
        libroId.setBorder(null);
        add(libroId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(51, 102, 255));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 180, 10));

        Devolver.setBackground(new java.awt.Color(51, 102, 255));
        Devolver.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        Devolver.setForeground(new java.awt.Color(255, 255, 255));
        Devolver.setText("Devuelto");
        Devolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DevolverMousePressed(evt);
            }
        });
        add(Devolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 180, 60));

        usuarioId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usuarioId.setForeground(new java.awt.Color(204, 204, 204));
        usuarioId.setText("Ingrese el id del usuario");
        usuarioId.setBorder(null);
        add(usuarioId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(51, 102, 255));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 180, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel2.setText("Usuario");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel3.setText("Libro");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        Devuelto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Devuelto.setText("¡La devolución se ha registrado con éxito!");
        add(Devuelto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void DevolverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DevolverMousePressed
        // TODO add your handling code here:
        try {
            int usuarioId = Integer.parseInt(this.usuarioId.getText());
            int libroId = Integer.parseInt(this.libroId.getText());

            prestamo = new Prestamo(usuarioId, libroId);
            prestamoDaoJdbc.devolver(prestamo);
            Devuelto.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Devolucion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DevolverMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Devolver;
    private javax.swing.JLabel Devuelto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField libroId;
    private javax.swing.JTextField usuarioId;
    // End of variables declaration//GEN-END:variables
}
