/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tech.calaverita.views;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import tech.calaverita.idao.*;
import tech.calaverita.models.*;

/**
 *
 * @author memoc
 */
public class EliminarRegistro extends javax.swing.JPanel {

    /**
     * Creates new form EliminarAutor
     */
    AutorDaoJdbc autorDaoJdbc;
    LibroDaoJdbc libroDaoJdbc;
    PrestamoDaoJdbc prestamoDaoJdbc;
    UsuarioDaoJdbc usuarioDaoJdbc;
    LibroAutorDaoJdbc libroAutorDaoJdbc;
    
    Autor autor;
    Libro libro;
    Prestamo prestamo;
    Usuario usuario;
    LibroAutor libroAutor; 
    
    String registro;
    
    public EliminarRegistro(String registro) {
        initComponents();
        
        autorDaoJdbc = new AutorDaoJdbc();
        libroDaoJdbc = new LibroDaoJdbc();
        prestamoDaoJdbc = new PrestamoDaoJdbc();
        usuarioDaoJdbc = new UsuarioDaoJdbc();
        
        this.Eliminado.setVisible(false);
        this.registro = registro;
        this.Registro.setText(this.Registro.getText().concat(registro));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Eliminado = new javax.swing.JLabel();
        Registro = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Eliminado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Eliminado.setText("¡Registro eliminado con éxito!");
        add(Eliminado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        Registro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Registro.setText("Id del ");
        add(Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        id.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        id.setForeground(new java.awt.Color(204, 204, 204));
        id.setText("Ingrese el id del registro a modificar");
        id.setBorder(null);
        add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 240, -1));

        jSeparator1.setForeground(new java.awt.Color(51, 102, 255));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 240, 10));

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Eliminar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 280, 130, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        int id;
        id = Integer.parseInt(this.id.getText());
        
        switch(registro){
            case "autor":
                autor = new Autor(id);
                try {
                    autorDaoJdbc.eliminar(autor);
                } catch (SQLException ex) {
                    Logger.getLogger(EliminarRegistro.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
            case "libro":
                libro = new Libro(id);
                try {
                    libroDaoJdbc.eliminar(libro);
                } catch (SQLException ex) {
                    Logger.getLogger(EliminarRegistro.class.getName()).log(Level.SEVERE, null, ex);
                }
            case "prestamo":
                prestamo = new Prestamo(id);
                try {
                    prestamoDaoJdbc.eliminar(prestamo);
                } catch (SQLException ex) {
                    Logger.getLogger(EliminarRegistro.class.getName()).log(Level.SEVERE, null, ex);
                }
            case "usuario":
                usuario = new Usuario(id);
                try {
                    usuarioDaoJdbc.eliminar(usuario);
                } catch (SQLException ex) {
                    Logger.getLogger(EliminarRegistro.class.getName()).log(Level.SEVERE, null, ex);
                }
            case "libroUsuario":
                libroAutor = new LibroAutor(id);
                try {
                    libroAutorDaoJdbc.eliminar(libroAutor);
                } catch (SQLException ex) {
                    Logger.getLogger(EliminarRegistro.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
        this.Eliminado.setVisible(true);
    }//GEN-LAST:event_jButton1MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Eliminado;
    private javax.swing.JLabel Registro;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
