/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tech.calaverita.views;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import tech.calaverita.idao.LibroDaoJdbc;
import tech.calaverita.models.Autor;
import tech.calaverita.models.Libro;

/**
 *
 * @author memoc
 */
public class ModificarLibro extends javax.swing.JPanel {

    /**
     * Creates new form AddUsuario
     */
    LibroDaoJdbc libroDaoJdbc;
    Libro libro;

    public ModificarLibro() {
        initComponents();
        libroDaoJdbc = new LibroDaoJdbc();
        Modificado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Modificado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        coverUrl = new javax.swing.JTextField();
        area = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        titulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        disponibleFisico = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        editorial = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        digitalUrl = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        text = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Modificado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Modificado.setText("¡Se ha modificado el libro con éxito!");
        add(Modificado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel1.setText("Disponible en físico");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 140, -1));

        coverUrl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        coverUrl.setForeground(new java.awt.Color(204, 204, 204));
        coverUrl.setText("Ingrese el Url del Cover");
        coverUrl.setBorder(null);
        add(coverUrl, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 270, -1));

        area.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        area.setForeground(new java.awt.Color(204, 204, 204));
        area.setText("Ingrese el área del libro");
        area.setBorder(null);
        add(area, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 270, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel3.setText("Área");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        titulo.setForeground(new java.awt.Color(204, 204, 204));
        titulo.setText("Ingrese el título del libro");
        titulo.setBorder(null);
        add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 270, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel4.setText("Url de Cover");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 90, -1));

        disponibleFisico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        disponibleFisico.setForeground(new java.awt.Color(204, 204, 204));
        disponibleFisico.setText("Ingrese si está disponible en físico");
        disponibleFisico.setBorder(null);
        add(disponibleFisico, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 270, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel5.setText("Título");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        editorial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editorial.setForeground(new java.awt.Color(204, 204, 204));
        editorial.setText("Ingrese la editorial");
        editorial.setBorder(null);
        add(editorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 270, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel6.setText("Url de digital");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 90, -1));

        digitalUrl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        digitalUrl.setForeground(new java.awt.Color(204, 204, 204));
        digitalUrl.setText("Ingrese el Url del digital");
        digitalUrl.setBorder(null);
        add(digitalUrl, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 270, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel7.setText("Editorial");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(51, 102, 255));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 270, 20));

        jSeparator2.setForeground(new java.awt.Color(51, 102, 255));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 270, 20));

        jSeparator3.setForeground(new java.awt.Color(51, 102, 255));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 270, 20));

        jSeparator4.setForeground(new java.awt.Color(51, 102, 255));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 270, 20));

        jSeparator5.setForeground(new java.awt.Color(51, 102, 255));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 270, 20));

        jSeparator6.setForeground(new java.awt.Color(51, 102, 255));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 270, 20));

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Modificar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 120, 60));

        id.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        id.setForeground(new java.awt.Color(204, 204, 204));
        id.setText("Ingrese el id del libro a modificar");
        id.setBorder(null);
        add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 270, -1));

        text.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        text.setText("Id");
        add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jSeparator7.setForeground(new java.awt.Color(51, 102, 255));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 270, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            int id = Integer.parseInt(this.id.getText());
            String titulo = this.titulo.getText();
            String editorial = this.editorial.getText();
            String area = this.area.getText();
            String coverUrl = this.coverUrl.getText();
            String digitalUrl = this.digitalUrl.getText();
            Boolean disponibleFisico = Boolean.parseBoolean(this.disponibleFisico.getText());

            libro = new Libro(id, titulo, editorial, area, coverUrl, digitalUrl, disponibleFisico);
            libroDaoJdbc.actualizar(libro);
            Modificado.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RegistrarAutor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Modificado;
    private javax.swing.JTextField area;
    private javax.swing.JTextField coverUrl;
    private javax.swing.JTextField digitalUrl;
    private javax.swing.JTextField disponibleFisico;
    private javax.swing.JTextField editorial;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel text;
    private javax.swing.JTextField titulo;
    // End of variables declaration//GEN-END:variables
}
