/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tech.calaverita.views;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import tech.calaverita.idao.AutorDaoJdbc;
import tech.calaverita.models.Autor;

/**
 *
 * @author memoc
 */
public class ModificarAutor extends javax.swing.JPanel {

    /**
     * Creates new form AddAutor
     */
    AutorDaoJdbc autorDaoJdbc = new AutorDaoJdbc();
    Autor autor;

    public ModificarAutor() {
        initComponents();

        Modificado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nacionalidad = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        Modificado = new javax.swing.JLabel();
        Text = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel1.setText("Nombre");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Modificar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 160, 60));

        nombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nombre.setForeground(new java.awt.Color(204, 204, 204));
        nombre.setText("Ingrese el nombre del autor");
        nombre.setBorder(null);
        add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel2.setText("Nacionalidad");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        nacionalidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nacionalidad.setForeground(new java.awt.Color(204, 204, 204));
        nacionalidad.setText("Ingreze la nacionalidad del autor");
        nacionalidad.setBorder(null);
        add(nacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(51, 102, 255));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 300, 10));

        jSeparator2.setForeground(new java.awt.Color(51, 102, 255));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 300, 10));

        Modificado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Modificado.setText("¡Se ha modificado al autor con éxito!");
        add(Modificado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        Text.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        Text.setText("Id");
        add(Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        id.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        id.setForeground(new java.awt.Color(204, 204, 204));
        id.setText("Ingrese el id del autor a modificar");
        id.setBorder(null);
        add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(51, 102, 255));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 300, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(this.id.getText());
            String nombre = this.nombre.getText();
            String nacionalidad = this.nacionalidad.getText();

            autor = new Autor(id, nombre, nacionalidad);
            autorDaoJdbc.actualizar(autor);
            Modificado.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ModificarAutor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Modificado;
    private javax.swing.JLabel Text;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField nacionalidad;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
