/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tech.calaverita.views;

import java.awt.BorderLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.JTable;
import tech.calaverita.controller.Controller;
import tech.calaverita.idao.PrestamoDaoJdbc;

/**
 *
 * @author memoc
 */
public class Prestamos extends javax.swing.JPanel {

    /**
     * Creates new form Autores
     */
    Controller controller;
    PrestamoDaoJdbc prestamo;

    public Prestamos(Controller controller) {
        initComponents();
        this.controller = controller;
        this.prestamo = new PrestamoDaoJdbc();
        try {
            prestamo.seleccionar(this);
        } catch (SQLException ex) {
            Logger.getLogger(Autores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public JTable getTable() {
        return this.jTable1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Registrar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setText("Ingrese el nombre o id del prestamo a buscar");
        jTextField1.setBorder(null);
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(51, 102, 255));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 460, 10));

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Buscar");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Fecha de Prestamo", "Fecha de Devolución", "Devuelto", "Id de usuario", "Id de libro"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 600, 300));

        Registrar.setBackground(new java.awt.Color(51, 102, 255));
        Registrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Registrar.setForeground(new java.awt.Color(255, 255, 255));
        Registrar.setText("Registrar");
        Registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RegistrarMousePressed(evt);
            }
        });
        add(Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, -1, -1));

        Eliminar.setBackground(new java.awt.Color(51, 102, 255));
        Eliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Eliminar.setForeground(new java.awt.Color(255, 255, 255));
        Eliminar.setText("Eliminar");
        add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, -1, -1));

        Modificar.setBackground(new java.awt.Color(51, 102, 255));
        Modificar.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        Modificar.setForeground(new java.awt.Color(255, 255, 255));
        Modificar.setText("Modificar");
        add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarMousePressed
        // TODO add your handling code here:
        RegistrarPrestamo vista = new RegistrarPrestamo();
        this.controller.setVista(vista);
        this.controller.setCabecera("Registrar Prestamo");
    }//GEN-LAST:event_RegistrarMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Modificar;
    private javax.swing.JButton Registrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
